# Generated by Django 4.2.4 on 2023-09-07 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("img", models.CharField(default="image_link", max_length=1000)),
                ("number", models.IntegerField(default=0, max_length=50)),
                ("link", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Waste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wname", models.CharField(max_length=100)),
                ("wpic", models.CharField(max_length=200)),
                ("wpre", models.CharField(max_length=250)),
                ("wrecipe", models.IntegerField(default=0, max_length=50)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.items"
                    ),
                ),
            ],
        ),
    ]
