# Generated by Django 4.2.6 on 2023-10-20 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Items",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("img", models.CharField(default="image_link", max_length=1000)),
                ("number", models.IntegerField(default=0, max_length=50)),
                ("link", models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Waste",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("wname", models.CharField(max_length=100)),
                ("wpic", models.CharField(max_length=200)),
                ("wpre", models.CharField(max_length=250)),
                ("wrecipe", models.IntegerField(default=0, max_length=50)),
                (
                    "link",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.items"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("itemlink", models.CharField(default="item_link", max_length=100)),
                ("recipename", models.CharField(max_length=100)),
                ("recipetime", models.IntegerField(default=0, max_length=50)),
                ("resdesc", models.CharField(default="description", max_length=1000)),
                ("recipeimg", models.CharField(default="image_url", max_length=500)),
                ("recipelink", models.CharField(max_length=200)),
                (
                    "wname",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="base.waste"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="RecipeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipedesc", models.CharField(max_length=1000)),
                ("recipeimage", models.CharField(default="image_url", max_length=500)),
                ("recipeingrediants", models.CharField(max_length=500)),
                ("recipesteps", models.CharField(max_length=1000)),
                (
                    "recipename",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="base.recipelist",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "recipename",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="base.recipelist",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        default=0,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
